import { 
  U2U_SEPOLIA_ADDRESS,
  SEPOLIA_BRIDGE_ADDRESS, 
  U2U_BRIDGE_ADDRESS,
  SEPOLIA_POOL,
  U2U_POOL,
  POCKET_PROTOCOL_SEPOLIA,
  POCKET_PROTOCOL_U2U,
  RIFF_TOKEN_SEPOLIA,
  RIFF_TOKEN_U2U,
  // Legacy RootStock imports
  WRBTC_SEPOLIA_ADDRESS, 
  ROOTSTOCK_BRIDGE_ADDRESS,
  ROOT_STACK_POOL,
  POCKET_PROTOCOL_ROOTSTOCK,
  RIFF_TOKEN_ROOTSTOCK
} from './addresses'
import WRBTC_ABI from './abiFiles/WRBTC.json'
import SEPOLIA_BRIDGE_ABI from './abiFiles/SepoliaBridgeNew.json'
import ROOTSTOCK_BRIDGE_ABI from './abiFiles/RootStackBridge.json'
import SEPOLIA_POOL_ABI from './abiFiles/SepoliaPool.json'
import ROOTSTACK_POOL_ABI from './abiFiles/RootStackPool.json'
import POCKET_PROTOCOL_ABI from './abiFiles/PocketProtocol.json'

export {
  // U2U addresses
  U2U_SEPOLIA_ADDRESS,
  SEPOLIA_BRIDGE_ADDRESS,
  U2U_BRIDGE_ADDRESS,
  SEPOLIA_POOL,
  U2U_POOL,
  POCKET_PROTOCOL_SEPOLIA,
  POCKET_PROTOCOL_U2U,
  RIFF_TOKEN_SEPOLIA,
  RIFF_TOKEN_U2U,
  // Legacy RootStock addresses
  WRBTC_SEPOLIA_ADDRESS,
  ROOTSTOCK_BRIDGE_ADDRESS,
  ROOT_STACK_POOL,
  POCKET_PROTOCOL_ROOTSTOCK,
  RIFF_TOKEN_ROOTSTOCK,
  // ABIs
  WRBTC_ABI,
  SEPOLIA_BRIDGE_ABI,
  ROOTSTOCK_BRIDGE_ABI,
  SEPOLIA_POOL_ABI,
  ROOTSTACK_POOL_ABI,
  POCKET_PROTOCOL_ABI,
}
